export const VelicinaPloda = {
    1: 'Semena pirinča',
    2: 'Semena maka',
    3: 'Semena susama',
    4: 'Semena narandže',
    5: 'Graška',
    6: 'Borovnice',
    7: 'Maline',
    8: 'Trešnje',
    9: 'Klementine',
    10: 'Limete',
    11: 'Šljive',
    12: 'Limuni',
    13: 'Nektarine',
    14: 'Jabuke',
    15: 'Avokada',
    16: 'Luka',
    17: 'Batata',
    18: 'Paradajza',
    19: 'Banane',
    20: 'Šargarepe',
    21: 'Tikvice',
    22: 'Manga',
    23: 'Klipa kukuruza',
    24: 'Karfiola',
    25: 'Glavice salate',
    26: 'Rastanjene glavice karfiole',
    27: 'Patlidžana',
    28: 'Butternut tikve',
    29: 'Kupusa',
    30: 'Kokosa',
    31: 'Ananasa',
    32: 'Manje dinje',
    33: 'Veće dinje',
    34: 'Honeydew dinje',
    35: 'Glavice zelene salate',
    36: 'Švajcarske blitve',
    37: 'Bundeve',
    38: 'Male lubenice',
    39: 'Lubenice',
    40: 'Male bundeve',
    41: 'Veće lubenice',
    42: 'Velike lubenice'
};
